/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import countrySelect from "strapi-plugin-country-select/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import vercelDeploy from "strapi-plugin-vercel-deploy/strapi-admin";
import openAi from "../../src/plugins/open-ai/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "country-select": countrySelect,
    "multi-select": multiSelect,
    "vercel-deploy": vercelDeploy,
    "open-ai": openAi,
  },
});
